version: "2"

services:
    consul:
        image: consul:0.7.2
        ports:
            - "8500:8500"
    quote1:
        image: agoncal/quote1:latest
        ports:
            - "8081:8081"
        links:
            - consul:consul
    quote2:
        image: agoncal/quote2:latest
        ports:
            - "8082:8082"
        links:
            - consul:consul
    quote3:
        image: agoncal/quote3:latest
        ports:
            - "8083:8083"
        links:
            - consul:consul
    quote4:
        image: agoncal/quote4:latest
        ports:
            - "8084:8084"
        links:
            - consul:consul
    quote5:
        image: agoncal/quote5:latest
        ports:
            - "8085:8085"
        links:
            - consul:consul
    quote6:
        image: agoncal/quote6:latest
        ports:
            - "8086:8086"
        links:
            - consul:consul
