version: "2"

services:
    consul:
        image: consul:0.7.2
        ports:
              - "8500:8500"
    quote1:
        image: agoncal/quote1:latest
        ports:
              - "8081:8081"
    quote2:
        image: agoncal/quote2:latest
        ports:
              - "8082:8082"
    quote3:
        image: agoncal/quote3:latest
        ports:
              - "8083:8083"
    quote4:
        image: agoncal/quote4:latest
        ports:
              - "8084:8084"
    quote5:
        image: agoncal/quote5:latest
        ports:
              - "8085:8085"
    quote6:
        image: agoncal/quote6:latest
        ports:
              - "8086:8086"
